package com.metamonjurul.service

import com.metamonjurul.model.*
import com.opencsv.CSVWriter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileWriter
import java.nio.charset.StandardCharsets

class CsvExportService {
    
    companion object {
        const val ADOBE_HEADERS = arrayOf("Filename", "Title", "Keywords", "Category", "Releases")
        
        // Pond5 Video format (for video/footage)
        const val POND5_VIDEO_HEADERS = arrayOf(
            "Clipid", "OriginalFilename", "Copyright", "Price", "name", 
            "City", "Region", "Country", "Created", "ClipSource", 
            "SpecifySource", "FrameRendering", "AspectRatio", 
            "Keywords", "KeywordsCheckbox", "PublicBin", "Description"
        )
        
        // Pond5 Audio format (for sound effects/music)
        const val POND5_AUDIO_HEADERS = arrayOf(
            "Clipid", "OriginalFilename", "Copyright", "Price", "name",
            "City", "Region", "Country", "Created", "ClipSource",
            "SpecifySource", "Keywords", "KeywordsCheckbox",
            "SoundType", "Pro", "Publisher", "Composer", "PublicBin", "Description"
        )
        
        const val SHUTTERSTOCK_HEADERS = arrayOf("Filename", "Description", "Keywords", "Categories", "Editorial", "Mature content", "illustration")
        const val FREEPIK_HEADERS = arrayOf("Filename", "Title", "Tags", "Category")
    }
    
    suspend fun exportToCsv(
        assets: List<StockAsset>,
        marketplace: Marketplace,
        outputFile: File,
        settings: AppSettings
    ): ExportResult = withContext(Dispatchers.IO) {
        outputFile.parentFile?.mkdirs()
        
        return@withContext try {
            when (marketplace) {
                Marketplace.ADOBE_STOCK -> exportAdobeStock(assets, outputFile)
                Marketplace.POND5 -> exportPond5(assets, outputFile)
                Marketplace.SHUTTERSTOCK -> exportShutterstock(assets, outputFile)
                Marketplace.FREEPIK -> exportFreepik(assets, outputFile)
            }
            ExportResult(success = true, filePath = outputFile.absolutePath, rowsExported = assets.size)
        } catch (e: Exception) {
            ExportResult(success = false, errorMessage = e.message)
        }
    }
    
    private fun exportAdobeStock(assets: List<StockAsset>, outputFile: File) {
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(ADOBE_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val keywords = metadata.keywords.take(50).joinToString(", ")
            val category = mapToAdobeCategory(metadata.category)
            
            writer.writeNext(arrayOf(
                asset.fileName,
                metadata.title,
                keywords,
                category,
                "" // Releases - would need model releases
            ))
        }
        writer.close()
    }
    
    private fun exportPond5(assets: List<StockAsset>, outputFile: File) {
        // Separate assets by type for correct Pond5 format
        val videoAssets = assets.filter { it.fileType.isVideoOrFootage() }
        val audioAssets = assets.filter { it.fileType.isAudio() }
        val imageAssets = assets.filter { it.fileType.isImageOrVector() }
        
        // Export video assets
        if (videoAssets.isNotEmpty()) {
            val videoFile = File(outputFile.parentFile, outputFile.nameWithoutExtension + "_video.csv")
            exportPond5Video(videoAssets, videoFile)
        }
        
        // Export audio assets
        if (audioAssets.isNotEmpty()) {
            val audioFile = File(outputFile.parentFile, outputFile.nameWithoutExtension + "_audio.csv")
            exportPond5Audio(audioAssets, audioFile)
        }
        
        // Export image/vector assets (use video format as default)
        if (imageAssets.isNotEmpty()) {
            val imageFile = File(outputFile.parentFile, outputFile.nameWithoutExtension + "_images.csv")
            exportPond5Video(imageAssets, imageFile) // Images use video-like format
        }
        
        // Also create a combined file for reference
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(POND5_VIDEO_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val keywords = metadata.keywords.take(50).joinToString(", ")
            val (soundType, pro, publisher, composer) = getPond5AudioFields(asset)
            
            writer.writeNext(arrayOf(
                "", // Clipid - auto-generated by Pond5
                asset.fileName,
                metadata.copyright ?: "", // Copyright
                metadata.price?.toString() ?: "49", // Price
                metadata.title,
                metadata.city ?: "", // City
                metadata.region ?: "", // Region
                metadata.country ?: "", // Country
                java.time.LocalDate.now().toString(), // Created
                "other", // ClipSource
                "", // SpecifySource
                keywords,
                "", // KeywordsCheckbox
                soundType, // SoundType (sfx/music) - only for audio
                pro, // Pro
                publisher, // Publisher
                composer, // Composer
                "", // PublicBin
                metadata.description
            ))
        }
        writer.close()
    }
    
    private fun exportPond5Video(assets: List<StockAsset>, outputFile: File) {
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(POND5_VIDEO_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val keywords = metadata.keywords.take(50).joinToString(", ")
            
            writer.writeNext(arrayOf(
                "", // Clipid
                asset.fileName,
                metadata.copyright ?: "",
                metadata.price?.toString() ?: "49",
                metadata.title,
                metadata.city ?: "",
                metadata.region ?: "",
                metadata.country ?: "",
                java.time.LocalDate.now().toString(),
                "other",
                "",
                metadata.frameRendering ?: "unknown",
                metadata.aspectRatio ?: "Other",
                keywords,
                "",
                "",
                metadata.description
            ))
        }
        writer.close()
    }
    
    private fun exportPond5Audio(assets: List<StockAsset>, outputFile: File) {
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(POND5_AUDIO_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val keywords = metadata.keywords.take(50).joinToString(", ")
            val (soundType, pro, publisher, composer) = getPond5AudioFields(asset)
            
            writer.writeNext(arrayOf(
                "", // Clipid
                asset.fileName,
                metadata.copyright ?: "",
                metadata.price?.toString() ?: "3",
                metadata.title,
                metadata.city ?: "",
                metadata.region ?: "",
                metadata.country ?: "",
                java.time.LocalDate.now().toString(),
                "other",
                "",
                keywords,
                "",
                soundType, // sfx or music
                pro, // Pro flag
                publisher ?: "Meta Monjurul", // Publisher
                composer ?: "Meta Monjurul", // Composer
                "",
                metadata.description
            ))
        }
        writer.close()
    }
    
    private fun getPond5AudioFields(asset: StockAsset): Triple<String, String, String?, String?> {
        val metadata = asset.metadata
        val isMusic = metadata.keywords.any { it.lowercase() in setOf("music", "song", "track", "background", "ambient", "corporate", "cinematic") }
        val soundType = if (isMusic) "music" else "sfx"
        val pro = if (asset.fileType == FileType.WAV || asset.fileType == FileType.AIFF) "true" else "false"
        return Triple(soundType, pro, metadata.publisher, metadata.composer)
    }
    
    private fun exportShutterstock(assets: List<StockAsset>, outputFile: File) {
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(SHUTTERSTOCK_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val keywords = metadata.keywords.take(50).joinToString(",")
            val categories = mapToShutterstockCategories(metadata.category)
            
            writer.writeNext(arrayOf(
                asset.fileName,
                metadata.description,
                keywords,
                categories,
                if (metadata.isEditorial) "yes" else "no",
                if (metadata.isMature) "yes" else "no",
                if (metadata.isIllustration) "yes" else "no"
            ))
        }
        writer.close()
    }
    
    private fun exportFreepik(assets: List<StockAsset>, outputFile: File) {
        val writer = CSVWriter(FileWriter(outputFile, StandardCharsets.UTF_8))
        writer.writeNext(FREEPIK_HEADERS)
        
        for (asset in assets) {
            val metadata = asset.metadata
            val tags = metadata.keywords.take(50).joinToString(",")
            
            writer.writeNext(arrayOf(
                asset.fileName,
                metadata.title,
                tags,
                metadata.category
            ))
        }
        writer.close()
    }
    
    private fun mapToAdobeCategory(category: String): String {
        return when (category.lowercase()) {
            "background", "texture", "pattern" -> "3" // Backgrounds
            "business", "finance", "money" -> "2" // Business
            "technology", "tech", "digital" -> "10" // Technology
            "nature", "landscape", "outdoor" -> "8" // Nature
            "people", "person", "human" -> "6" // People
            "abstract", "art", "design" -> "1" // Abstract
            else -> "3" // Default to Backgrounds
        }
    }
    
    private fun mapToShutterstockCategories(category: String): String {
        return when (category.lowercase()) {
            "background", "texture", "pattern" -> "backgrounds"
            "business", "finance", "money" -> "business"
            "technology", "tech", "digital" -> "technology"
            "nature", "landscape", "outdoor" -> "nature"
            "people", "person", "human" -> "people"
            "abstract", "art", "design" -> "abstract"
            else -> "backgrounds"
        }
    }
    
    suspend fun exportAllMarketplaces(
        assets: List<StockAsset>,
        baseDir: File,
        settings: AppSettings
    ): Map<Marketplace, ExportResult> = withContext(Dispatchers.IO) {
        val results = mutableMapOf<Marketplace, ExportResult>()
        
        for (marketplace in settings.defaultMarketplaces) {
            val fileName = "MetaMonjurul_${marketplace.name}_${java.time.LocalDate.now()}.csv"
            val outputFile = File(baseDir, fileName)
            val result = exportToCsv(assets, marketplace, outputFile, settings)
            results[marketplace] = result
        }
        
        results
    }
}

data class ExportResult(
    val success: Boolean,
    val filePath: String = "",
    val rowsExported: Int = 0,
    val errorMessage: String? = null
)